### ISSUE TITLE
Feature or bug?

### ISSUE THREAD

**Issue by tvvocold** [ryanj/gist-reveal.it#36]
I build a clone site.The dmain.com/gist_id  is working but the domain.com/?set_Tocken isn't.
Is this a new feature(evrey body could use it) or bug(i cannot set a secret tocken)?

**Comment by ryanj** [comment]
domain.com/?set_Tocken=MY_SECRET_CODE only sets a token in your browser.

You need to use `rhc env set REVEAL_SOCKET_SECRET=MY_SECRET_CODE` and `rhc app restart` to set a matching secret on the server.

Debug info is printed to the server log and the browser console log.

**Comment by tvvocold** [comment]
thx.
